import React from "react";
import { Bot } from "lucide-react";

interface AiGeneratedBadgeProps {
  label?: string;
  size?: "sm" | "xs";
  className?: string;
}

export const AiGeneratedBadge: React.FC<AiGeneratedBadgeProps> = ({
  label = "AI Generated",
  size = "sm",
  className = "",
}) => (
  <span
    className={`inline-flex items-center space-x-1 font-extrabold uppercase tracking-wider rounded-full bg-gradient-to-r from-violet-600/20 to-fuchsia-600/15 border border-violet-500/30 text-violet-600 dark:text-violet-300 ${
      size === "sm" ? "px-2.5 py-1 text-[10px]" : "px-2 py-0.5 text-[9px]"
    } ${className}`}
    title="Generated by the VeraFit AI recommendation agents"
  >
    <Bot className={size === "sm" ? "w-3 h-3" : "w-2.5 h-2.5"} />
    <span>{label}</span>
  </span>
);
